"""Ports the application layer depends on."""

from typing import Protocol

from eva.domain.models import ActionRequest, AgentStep


class AgentPort(Protocol):
    def ask(self, message: str) -> AgentStep: ...

    def resume(self, decisions: list[dict[str, str]]) -> AgentStep: ...

    def forget_last_turn(self) -> None: ...

    def cancel(self) -> None: ...

    def steer(self, message: str) -> None: ...

    def take_unread(self) -> list[str]: ...


class ApprovalPort(Protocol):
    def approve(self, action: ActionRequest) -> bool: ...
